# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('query', models.CharField(max_length=80, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id1', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ScoreMovie',
            fields=[
                ('score', models.IntegerField(default=1)),
                ('movie', models.CharField(max_length=80, primary_key=True, serialize=False)),
            ],
        ),
    ]
